basePath: /
definitions:
  main.Status:
    properties:
      status:
        example: OK
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Fiber example for openapi spec generation
  title: Fiber Example API
  version: "1.0"
paths:
  /actuator/health/{id}:
    get:
      consumes:
      - application/json
      description: get string by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Status'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Show an account
      tags:
      - actuator
swagger: "2.0"
